apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    course: docker
    duration: 25hrs
    trainer: siva
  annotatations:
    org.docker.kubernetes.image.maintainer: siva
spec:
  containers:
    - name: nginx
      image: nginx