apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - name: stress
      image: naveenreddy369/stress
      imagePullPolicy: Always
      command: ["sleep", "200"]
      resources:
        requests:
          memory: "20Mi"
          cpu: "150m"    #1CPU= 1000m
        limits:
          memory: "30Mi"
          cpu: "200"

#Stress: It will exhaust all the resorces.

# kubectl apply -f 04-resources.yaml
# kubectl get pods -o wide
# kubectl exec -it stress -- bash
# stress-ng --help
# stress-ng --cpu 1

# Go check CPU utilization in the respective NODE server by using top command.