apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - name: stress
      image: naveenreddy369/stress
      imagePullPolicy: Always
      command: ["sleep", "200"]
      resources:
        requests:
          memory: "20Mi"
          cpu: "150m"    #1CPU= 1000m
        limits:
          memory: "30Mi"
          cpu: "200"