apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password

#Secret is referred from - k8s-resources-techworldwithsiva/secrets/01-secret.yaml

# kubectl apply -f 08-secret-pod.yaml
# kubectl exec -it secret-pod -- /bin/bash