---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    server: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    server: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# NodePort
# Exposes the Service on each Node's IP at a static port (the NodePort).
# Just like in docker we exposed nginx container at host level(host port) Here we are exposing at node level (Node port). K8s willn randomly open these ports. These ports are called as ephemeral ports. (ephemeral ports range linux: 32768-60999)
# NOTE: If we use NodePort, it will open the port in each and every node inside the cluster.

# USER----->NODE1:<NODE-PORT> --->Cluster IP --> Container
#           NODE2:<NODE-PORT> --->Cluster IP --> Container

# kubectl apply -f 02-service.yaml
# [ec2-user@ip-172-31-10-32 service]$ kubectl get service
# NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
# kubernetes      ClusterIP   10.100.0.1       <none>        443/TCP        105m
# nginx-service   NodePort    10.100.146.181   <none>        80:30507/TCP   20s
#  kubectl get pods -o wide
#  Open browser, PUBLIC_IP-of-NODE:30507