apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
      - name: fluentd-elasticsearch
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log

# kubectl apply -f 04-host-path.yaml
# kubectl get pods
# kubectl get pods -n kube-system

# This configuration deploys Fluentd with Elasticsearch output as a DaemonSet in the "kube-system" namespace. Each node in the cluster will have a Fluentd container running as a Pod, processing log files from the host's "/var/log" directory and forwarding them to Elasticsearch for centralized log storage and analysis.