---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-dynamic-pvc
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 14Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: my-ebs-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: my-ebs-volume
    persistentVolumeClaim:
      claimName: my-ebs-dynamic-pvc

# kubectl apply -f 06-ebs-dynamic.yaml
# kubectl get pods
# NOTE: Since we mention the reclaimPolicy: Delete, if we delete the pod automatically EBS volume is also deleted in AWS Console.