apiVersion: v1
kind: ConfigMap
metadata:
  name: course-config
data:
  course: docker
  duration: 30hr

# kubectl apply -f 01-configMap.yaml
# kubectl get configmaps

# In real-time projects, it is not recommended to make direct changes to Pod definition files for updating configuration settings. Instead, a best practice is to use ConfigMaps in Kubernetes and refer to the key-value pairs as environment variables within the Pod.

# A ConfigMap is an API object used to store non-confidential data in key-value pairs. Pods can consume ConfigMaps as environment variables, command-line arguments, or as configuration files in a volume.