apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: c2l2YWt1bWFy
  password: c2l2YWt1bWFyMTIz


# A Secret is an object that contains a small amount of sensitive data such as a password, a token, or a key. 
# Opaque is the default Secret type


# [ec2-user@ip-172-31-10-222 pod]$ echo -n sivakumar | base64
# c2l2YWt1bWFy
# [ec2-user@ip-172-31-10-222 pod]$ echo -n sivakumar123 | base64
# c2l2YWt1bWFyMTIz

# kubectl apply -f 01-secret.yaml
# kubectl describe secret mysecret

# Name:         mysecret
# Namespace:    default
# Labels:       <none>
# Annotations:  <none>

# Type:  Opaque

# Data
# ====
# password:  12 bytes
# username:  9 bytes